swagger: "2.0"

info:
  version: "2.0.0"
  title: Room

schemes:
- "https"
- "http"

securityDefinitions:
  basicAuth:
    type: basic
  tokenAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
  Bearer:
    type: apiKey
    name: Authorization
    in: header

paths:
  /users:
    $ref: "./users/users/users.yaml"
  /user/{uid}:      
    $ref: "./users/user/user.yaml"            
  /avatars:
    $ref: "./avatars/avatars/avatars.yaml"
  /avatar/{avatar_id}:
    $ref: "./avatars/avatar/avatar.yaml"
  /rooms:
    $ref: "./rooms/rooms/rooms.yaml"
  /room/{room_id}:
    $ref: "./rooms/room/room.yaml"
  /chats:
    $ref: "./chats/chats/chats.yaml"
  /chat/{receiver_id}:
    $ref: "./chats/chat/chat.yaml"
  /files/{room_id}:
    $ref: "./files/files/files.yaml"
  /file/{file_id}:
    $ref: "./files/file/file.yaml"
  /providers/{provider_id}:
    $ref: "./files/providers/providers.yaml"
  /comments/{file_id}:
    $ref: "./comments/comments/comments.yaml"
  /threads/{comment_id}:
    $ref: "./comments/threads/threads.yaml"
  /thread/{thread_id}:
    $ref: "./comments/thread/thread.yaml"